# .github/workflows/test-e2e.yml
name: E2E Tests (Real AWS)

on:
  push:
    branches: [main]
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  e2e-tests:
    name: E2E Tests (Real AWS)
    runs-on: ubuntu-latest
    
    # Only run if AWS credentials are available
    if: |
      github.ref == 'refs/heads/main' ||
      github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: cn-north-1
      
      - name: Run E2E tests
        env:
          TEST_BUCKET: ${{ secrets.TEST_BUCKET || 't01logs' }}
          AWS_REGION: cn-north-1
        run: |
          pytest tests/e2e/ -v -m "e2e or real_aws" --tb=short
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "E2E tests failed! Check logs for details."
          # Add Slack/email notification here if needed